### ISSUE TITLE
块级格式化上下文 BFC原理

### ISSUE THREAD

**Issue by lxinr** [lxinr/interview-question#14]
### BFC的触发

只要元素满足下面任一条件即可触发 BFC 特性:

- body 根元素
- 浮动元素：float 除 none 以外的值
- 绝对定位元素：position (absolute、fixed)
- display 为 inline-block、table-cells、flex
- overflow 除了 visible 以外的值 (hidden、auto、scroll)

### BFC的约束规则

- 内部的Box会在垂直方向上一个接一个的放置
- 垂直方向上的距离由margin决定。（完整的说法是：属于同一个BFC的两个相邻Box的margin会发生重叠（塌陷），与方向无关。）
- 每个元素的左外边距与包含块的左边界相接触（从左向右），即使浮动元素也是如此。（这说明BFC中子元素不会超出他的包含块，而position为absolute的元素可以超出他的包含块边界）
- BFC的区域不会与float的元素区域重叠
- 计算BFC的高度时，浮动子元素也参与计算
- BFC就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面元素，反之亦然

#### 1、防止margin重叠，即解决margin塌陷问题

在p外面包裹一层容器wrap，并触发该容器生成一个新BFC。那么两个P便不属于同一个BFC，就不会发生margin重叠了

```css
<style>
    .wrap {
        overflow: hidden;
    }
    p {
        color: #f55;
        background: #fcc;
        width: 200px;
        line-height: 100px;
        text-align:center;
        margin: 100px;
    }
</style>
<body>
    <p>content1</p>
    <div class="wrap">
        <p>content2</p>
    </div>
</body>
```
