### ISSUE TITLE
2021/03/07 - 对flex的理解

### ISSUE THREAD

**Issue by lxinr** [lxinr/interview-question#67]
#### flex的概念
>  flex布局的主要思想是让容器能使其子元素的宽高（或其他属性）能够以最好的方式去填充可用空间（主要是去适应不同的设备跟分辨率）。一个flex弹性盒子能让子元素填充可用空间或者为了阻止子元素超出区域而进行收缩

#### 1. flex-direction

> flex-direction属性决定主轴的方向（即项目的排列方向）

```html
.box {
  flex-direction: row | row-reverse | column | column-reverse;
}
//依次表示主轴为水平方向，起点在左端（默认）
//主轴为水平方向，起点在右端
//主轴为垂直方向，起点在上沿
//主轴为垂直方向，起点在下沿
```

#### 2. flex-wrap

> 默认情况下，项目都排在一条线（又称"轴线"）上。flex-wrap属性定义，如果一条轴线排不下，如何换行

```html
.box{
  flex-wrap: nowrap | wrap | wrap-reverse;
  //不换行
  //换行，第一行在上方
  //换行，第一行在下方
}
```

#### 3. justify-content
> justify-content属性定义了项目在主轴上的对齐方式

```html
.box {
  justify-content: flex-start | flex-end | center | space-between | space-around;
  //依次是左对齐（默认值）
  //右对齐
  //居中
  //两端对齐，项目之间的间隔都相等
  //每个项目两侧的间隔相等。所以，项目之间的间隔比项目与边框的间隔大一倍
}
```

#### 4. align-items
> align-items属性定义项目在交叉轴上如何对齐，即与主轴垂直的方向

```html
.box {
  align-items: flex-start | flex-end | center | baseline | stretch;
  //依次是交叉轴的起点对齐。
  //交叉轴的终点对齐。
  //交叉轴的中点对齐。
  //项目的第一行文字的基线对齐。
  //如果项目未设置高度或设为auto，将占满整个容器的高度（默认值）
}
```

#### 5. order
> order属性定义项目的排列顺序。数值越小，排列越靠前，默认为0

#### 6. flex-grow

> flex-grow属性定义项目的放大比例，默认为0，即如果存在**剩余空间**，也不放大，如果不存在**剩余空间**，即子容器宽度大于等于父容器宽度，则设置flex-grow也无效

![https://static.lxinr.com/2021/0307/1615114381127.png](https://static.lxinr.com/2021/0307/1615114381127.png)

如上图，所谓的剩余空间就是`500-100-150-100=150`

假如我们给对应的A/B/C分别设置`flex-grow`：

```html
.a {
 flex-grow: 1
}
.b {
 flex-grow: 1
}
.c {
 flex-grow: 3
}
```

此时三个div的宽度分别为`100 + 150 * (1/1+1+3)`、`150 + 150 * (1/1+1+3)`、`100 + 150 * (1/1+1+3)`

![https://static.lxinr.com/2021/0307/1615114815735.png](https://static.lxinr.com/2021/0307/1615114815735.png)

**如果出现flex-grow总和小于1？那么计算剩余空间的结果有所变化。比如：flex-grow设置为0.1, 0.2, 0.3， 原溢出空间为200，实际溢出空间：200 * （0.1 + 0.2 + 0.3）/ 1 = 120**

#### 7. flex-shrink

> 与flex-grow所需的**剩余空间**概念相对的，即子容器宽度大于父容器宽度，此时多出来的宽度被称为**溢出空间**，flex-shrink指定了 flex 元素的收缩规则，默认值是 1

如上例子：

```css
.container {
    width: 500px;
}

.a{
    width: 300px;
    background-color:#ff4466;
    flex-shrink: 1;
}
.b{
    width: 150px;
    background-color:#42b983;
    flex-shrink: 2;
}
.c{
    width: 200px;
    background-color:#61dafb;
    flex-shrink: 3;
}
```

溢出空间`O = 300 + 150 + 200 - 500 = 150`
总压缩权重`SUM = 1*300 + 2*150 + 3*200 = 1200`
计算各自的压缩率：
`r1 = 1*300 / SUM`
`r2 = 2*150 / SUM`
`r3 = 3*200 / SUM`

此时，各个元素的宽度：
`w1 = 300 - O*r1 = 300 - 37.5`
`w2 = 150 - O*r2 = 150 - 37.5`
`w3 = 200 - O*r3 = 200 - 75`

![https://static.lxinr.com/2021/0307/1615115719904.png](https://static.lxinr.com/2021/0307/1615115719904.png)

**如果出现flex-shrink总和小于1？那么计算溢出空间（收缩总和）的结果有所变化。比如：shrink设置为0.1, 0.2, 0.3， 原溢出空间为200，实际溢出空间：200 * （0.1 + 0.2 + 0.3）/ 1 = 120**

#### 8. flex-basis

> flex-basis指定了 flex 元素在主轴方向上的初始大小

优先级：

```html
max-width/min-width > flex-basis > width > box
```

#### 9. flex（重点）

> flex 是 flex-grow、flex-shrink、flex-basis的缩写，默认值为`0 1 auto`

##### 当 flex 取值为 none，则计算值为 0 0 auto
```scss
div{
    diaplay:flex;
    .div {
        flex-grow: 0;
        flex-shrink: 0;
        flex-basis: auto;
    }   
}
```

##### 当 flex 取值为 auto，则计算值为 1 1 auto
```scss
div{
    diaplay:flex;
    .div {
        flex-grow: 1;
        flex-shrink: 1;
        flex-basis: auto;
    }   
}
```

##### 当 flex 取值为一个非负数字，则 flex-grow 数字，flex-shrink 取 1，flex-basis 取 0%（最常用）
```scss
div{
    diaplay:flex;
    .div {
        flex-grow: 1; // 设置的值
        flex-shrink: 1;
        flex-basis: 0%;
    }   
}
```

##### 当 flex 取值为一个长度或百分比，则视为 flex-basis 值，flex-grow 取 1，flex-shrink 取 1
```scss
div{
    diaplay:flex;
    .div {
        flex-grow: 1;
        flex-shrink: 1;
        flex-basis: 200px; // 设置的值
    }   
}
```

##### 当 flex 取值为两个非负数字，则分别视为 flex-grow 和 flex-shrink 的值，flex-basis 取 0%
```scss
div{
    diaplay:flex;
    .div {
        flex-grow: 0; // 第一个值
        flex-shrink: 1; // 第二个值
        flex-basis: 0%;
    }   
}
```

##### 当 flex 取值为一个非负数字和一个长度或百分比，则分别视为 flex-grow 和 flex-basis 的值，flex-shrink 取 1
```scss
div{
    diaplay:flex;
    .div {
        flex-grow: 0; // 第一个值
        flex-shrink: 1; 
        flex-basis: 200px; // 第二个值
    }   
}
```

#### 10. align-self

> align-self属性允许单个项目有与其他项目不一样的对齐方式，可覆盖align-items属性。默认值为auto，表示继承父元素的align-items属性，如果没有父元素，则等同于stretch

```css
.item {
  align-self: auto | flex-start | flex-end | center | baseline | stretch;
  //这个其实就是在项目里用align-items 注：auto为默认值
}
```

参考文章：

[1. 深入理解 flex-grow、flex-shrink、flex-basis](https://juejin.cn/post/6844904016439148551#heading-8)
[2. flex深度剖析-解决移动端适配问题！](https://juejin.cn/post/6844904097850589191#heading-35)
